-- MySQL Script generated by MySQL Workbench
-- Sun Sep  5 18:50:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Fonoteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Fonoteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Fonoteca` DEFAULT CHARACTER SET utf8 ;
USE `Fonoteca` ;

-- -----------------------------------------------------
-- Table `Fonoteca`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fonoteca`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fonoteca`.`Fonoteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fonoteca`.`Fonoteca` (
  `idFonoteca` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idFonoteca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fonoteca`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fonoteca`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `estado` BIT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT now(),
  `tipo_usuario_idtipo_usuario` INT NOT NULL,
  `Fonoteca_idFonoteca` INT NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_tipo_usuario_idx` (`tipo_usuario_idtipo_usuario` ASC) ,
  INDEX `fk_usuarios_Fonoteca1_idx` (`Fonoteca_idFonoteca` ASC) ,
  CONSTRAINT `fk_usuarios_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_idtipo_usuario`)
    REFERENCES `Fonoteca`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_Fonoteca1`
    FOREIGN KEY (`Fonoteca_idFonoteca`)
    REFERENCES `Fonoteca`.`Fonoteca` (`idFonoteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fonoteca`.`Categorías`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fonoteca`.`Categorías` (
  `idCategorías` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorías`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fonoteca`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fonoteca`.`Material` (
  `idMaterial` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `banda` VARCHAR(45) NOT NULL,
  `year` YEAR NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `sello` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `Categorías_idCategorías` INT NOT NULL,
  `estado` BIT NULL,
  `Fonoteca_idFonoteca` INT NOT NULL,
  PRIMARY KEY (`idMaterial`),
  INDEX `fk_Material_Categorías1_idx` (`Categorías_idCategorías` ASC) ,
  INDEX `fk_Material_Fonoteca1_idx` (`Fonoteca_idFonoteca` ASC) ,
  CONSTRAINT `fk_Material_Categorías1`
    FOREIGN KEY (`Categorías_idCategorías`)
    REFERENCES `Fonoteca`.`Categorías` (`idCategorías`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_Fonoteca1`
    FOREIGN KEY (`Fonoteca_idFonoteca`)
    REFERENCES `Fonoteca`.`Fonoteca` (`idFonoteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fonoteca`.`Banda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fonoteca`.`Banda` (
  `idBanda` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idBanda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fonoteca`.`Banda_has_Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fonoteca`.`Banda_has_Material` (
  `idBandas` INT NOT NULL,
  `Banda_idBanda` INT NOT NULL,
  `Material_idMaterial` INT NOT NULL,
  INDEX `fk_Banda_has_Material_Banda1_idx` (`Banda_idBanda` ASC) ,
  INDEX `fk_Banda_has_Material_Material1_idx` (`Material_idMaterial` ASC) ,
  CONSTRAINT `fk_Banda_has_Material_Banda1`
    FOREIGN KEY (`Banda_idBanda`)
    REFERENCES `Fonoteca`.`Banda` (`idBanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banda_has_Material_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `Fonoteca`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
